### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Burstaholic** [edouard-lopez/fish-syntax-highlighting#1]
Hi, it's unclear to me how to actually use this project (with WebStorm, but it should be the same for all IntelliJ-based editors).

Using `Import Settings` with the .jar file produces an error ('file contains no settings to import'), and the `IntelliJ IDEA Global Settings` file is empty, so I'm not sure what to do with it.

Thanks for your help!

**Comment by Burstaholic** [comment]
Figured it out: simply copy `fish.xml` from JetBrains->filetypes into your editor's `config/filetypes` directory (create directory if needed), e.g. `~/.WebStorm2017.1/config/filetypes/fish.xml`.

I'm not sure what the makefile and .jar are for.

**Comment by edouard-lopez** [comment]
Thanks @Burstaholic I updated the readme following your feedback.
